wandb_version: 1

C:
  desc: null
  value: 1.0
class_weight:
  desc: null
  value: null
dual:
  desc: null
  value: false
fit_intercept:
  desc: null
  value: true
intercept_scaling:
  desc: null
  value: 1
l1_ratio:
  desc: null
  value: null
max_iter:
  desc: null
  value: 100
multi_class:
  desc: null
  value: auto
n_jobs:
  desc: null
  value: null
penalty:
  desc: null
  value: l2
random_state:
  desc: null
  value: null
solver:
  desc: null
  value: lbfgs
tol:
  desc: null
  value: 0.0001
verbose:
  desc: null
  value: 0
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715606820
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
test_size:
  desc: null
  value: 0.2
train_len:
  desc: null
  value: 712
test_len:
  desc: null
  value: 179
